# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: DEBUG
        com.pluralsight.springbatch.patientbatchloader: DEBUG
        
spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./h2db/db/patientbatchloader-dev;
        username: PatientBatchLoader
        password:
    h2:
        console:
            enabled: true
    jpa:
        database-platform: com.pluralsight.springbatch.patientbatchloader.config.FixedH2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    messages:
        cache-seconds: 1

liquibase:
    contexts: dev

# ===================================================================
# Application specific properties
# ===================================================================

application:
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: true
            report-frequency: 60 # in seconds
