version: '2'
services:
    patientbatchloader-app:
        image: patientbatchloader
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://localhost:1433;database=patient
            - APP_SLEEP=30 
        ports:
            - 8080:8080
    patientbatchloader-mssql:
        extends:
            file: mssql.yml
            service: patientbatchloader-mssql